services:
  mealie-planner:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      # Persist the SQLite database and config file
      - ./planner.db:/app/planner.db
      - ./config.json:/app/config.json